package org.kohsuke.graphviz;

/**
 * <a href="http://www.graphviz.org/doc/info/shapes.html">Node Shapes</a>
 *
 * @author Kohsuke Kawaguchi
 */
public enum Shape {
    BOX, POLYGON, ELLIPSE, OVAL,
    CIRCLE, POINT, EGG, TRIANGLE,
    PLAINTEXT, PLAIN, DIAMOND, TRAPEZIUM,
    PARALLELOGRAM, HOUSE, PENTAGON, HEXAGON,
    SEPTAGON, OCTAGON, DOUBLECIRCLE, DOUBLEOCTAGON,
    TRIPLEOCTAGON, INVTRIANGLE, INVTRAPEZIUM, INVHOUSE,
    MDIAMOND, MSQUARE, MCIRCLE, RECT,
    RECTANGLE, SQUARE, STAR, NONE,
    UNDERLINE, CYLINDER, NOTE, TAB,
    FOLDER, BOX3D, COMPONENT, PROMOTER,
    CDS, TERMINATOR, UTR, PRIMERSITE,
    RESTRICTIONSITE, FIVEPOVERHANG, THREEPOVERHANG, NOVERHANG,
    ASSEMBLY, SIGNATURE, INSULATOR, RIBOSITE,
    RNASTAB, PROTEASESITE, PROTEINSTAB, RPROMOTER,
    RARROW, LARROW, LPROMOTER
}
